version: '3.5'

services:
  mariadb:
    image: mariadb:10.4.13
    container_name: mariadb
    volumes:
      - ../data/mariadb:/var/lib/mysql
      # - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=dbYentu
      - MYSQL_USER=yentu
      - MYSQL_PASSWORD=wez7Wt6Fa9zY
      - MYSQL_ROOT_PASSWORD=RENJkgqeex9Q
    networks:
      - myNetworkBak

  redisdb:
    image: redis:5.0
    container_name: dbredis
    command: redis-server --requirepass FdxJsQFJUSKuXSdqUpGn
    ports:
      - 6379:6379
    restart: always
    networks:
      - myNetworkBak

  mongodb:
    image: mongo:4.0
    container_name: dbmongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: FdxJsQFJUSKuXSdqUpGn
    volumes:
      - ../data/mongo:/data/db
    restart: always
    networks:
      - myNetworkBak

  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
      - 5672:5672
      - 15672:15672
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=FdxJsQFJUSKuXSdqUpGn
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    restart: always
    networks:
      - myNetworkBak

  minio:
    image: minio/minio:RELEASE.2020-03-19T21-49-00Z
    container_name: minio
    volumes:
      - ../data/rabbitmq:/export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: FdxJsQFJUSKuXSdqUpGn

networks:
  myNetworkBak:
    external: true
